services:
    hg_simple_content.simple_content_manager:
        class: Hgabka\SimpleContentBundle\Helper\SimpleContentManager
        arguments: ['@doctrine', '@hgabka_utils.hgabka_utils', '%kernel.cache_dir%']
        public: true

    hg_simple_content.simple_content_twig_extension:
        class: Hgabka\SimpleContentBundle\Twig\HgabkaSimpleContentTwigExtension
        arguments: ['@hg_simple_content.simple_content_manager']
        public: false
        tags:
            - { name: twig.extension }

    hg_simple_content.admin.simple_content:
        class: Hgabka\SimpleContentBundle\Admin\SimpleContentAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\SimpleContentBundle\Entity\SimpleContent, controller: Hgabka\SimpleContentBundle\Controller\SimpleContentAdminController, manager_type: orm, group: hg_simple_content.group, icon: '<i class="fa fa-file"></i>', label: hg_simple_content.admin.label, label_catalogue: 'HgabkaSimpleContentBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        calls:
            - [setManager, ['@hg_simple_content.simple_content_manager']]
            - [setSecurity, ['@security.helper']]
            - [setUtils, ['@hgabka_utils.hgabka_utils']]
            - [setEditorMode, ['%hgabka_simple_content.editor_mode%']]

    Hgabka\SimpleContentBundle\Helper\SimpleContentManager:
        alias: 'hg_simple_content.simple_content_manager'
        public: true
    
    Hgabka\SimpleContentBundle\Controller\SimpleContentAdminController:
        autowire: true
        autoconfigure: true
